// <auto-generated />
namespace EDI_NCPDP_Ingestion.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.2")]
    public sealed partial class EDI_NCPDP : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EDI_NCPDP));
        
        string IMigrationMetadata.Id
        {
            get { return "202605091954495_EDI_NCPDP"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
