// <auto-generated />
using System;
using EDI837Ingestion.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EDI837Ingestion.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260709162026_InitialEdi837")]
    partial class InitialEdi837
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EDI837Ingestion.EF.Entities.Claim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BillingProviderId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ClaimDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ClaimNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int");

                    b.Property<int?>("PayerId")
                        .HasColumnType("int");

                    b.Property<int?>("RenderingProviderId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalChargeAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TransactionSetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BillingProviderId");

                    b.HasIndex("PatientId");

                    b.HasIndex("PayerId");

                    b.HasIndex("RenderingProviderId");

                    b.HasIndex("TransactionSetId");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("EDI837Ingestion.EF.Entities.ClaimLineItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClaimId")
                        .HasColumnType("int");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Modifiers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProcedureCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ServiceDateFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ServiceDateTo")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("UnitCharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Units")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.ToTable("ClaimLineItems");
                });

            modelBuilder.Entity("EDI837Ingestion.EF.Entities.Diagnosis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClaimId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.ToTable("Diagnoses");
                });

            modelBuilder.Entity("EDI837Ingestion.EF.Entities.FunctionalGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FunctionalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupControlNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InterchangeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InterchangeId");

                    b.ToTable("FunctionalGroups");
                });

            modelBuilder.Entity("EDI837Ingestion.EF.Entities.Interchange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("IsaControlNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ReceiverId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("IsaControlNumber", "SenderId", "ReceiverId");

                    b.ToTable("Interchanges");
                });

            modelBuilder.Entity("EDI837Ingestion.EF.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("EDI837Ingestion.EF.Entities.Payer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayerIdentifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PayerIdentifier");

                    b.ToTable("Payers");
                });

            modelBuilder.Entity("EDI837Ingestion.EF.Entities.Provider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Npi")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Npi");

                    b.ToTable("Providers");
                });

            modelBuilder.Entity("EDI837Ingestion.EF.Entities.RawEdiFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FileName");

                    b.ToTable("RawEdiFiles");
                });

            modelBuilder.Entity("EDI837Ingestion.EF.Entities.TransactionSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FunctionalGroupId")
                        .HasColumnType("int");

                    b.Property<int?>("InterchangeId")
                        .HasColumnType("int");

                    b.Property<int?>("RawEdiFileId")
                        .HasColumnType("int");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionControlNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("TransactionDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FunctionalGroupId");

                    b.HasIndex("InterchangeId");

                    b.HasIndex("RawEdiFileId");

                    b.HasIndex("TransactionControlNumber");

                    b.ToTable("TransactionSets");
                });

            modelBuilder.Entity("EDI837Ingestion.EF.Entities.ValidationIssue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClaimId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ErrorCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Segment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TransactionSetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.HasIndex("TransactionSetId");

                    b.ToTable("ValidationIssues");
                });

            modelBuilder.Entity("EDI837Ingestion.EF.Entities.Claim", b =>
                {
                    b.HasOne("EDI837Ingestion.EF.Entities.Provider", "BillingProvider")
                        .WithMany()
                        .HasForeignKey("BillingProviderId");

                    b.HasOne("EDI837Ingestion.EF.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EDI837Ingestion.EF.Entities.Payer", "Payer")
                        .WithMany("Claims")
                        .HasForeignKey("PayerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EDI837Ingestion.EF.Entities.Provider", "RenderingProvider")
                        .WithMany()
                        .HasForeignKey("RenderingProviderId");

                    b.HasOne("EDI837Ingestion.EF.Entities.TransactionSet", "TransactionSet")
                        .WithMany("Claims")
                        .HasForeignKey("TransactionSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BillingProvider");

                    b.Navigation("Patient");

                    b.Navigation("Payer");

                    b.Navigation("RenderingProvider");

                    b.Navigation("TransactionSet");
                });

            modelBuilder.Entity("EDI837Ingestion.EF.Entities.ClaimLineItem", b =>
                {
                    b.HasOne("EDI837Ingestion.EF.Entities.Claim", "Claim")
                        .WithMany("LineItems")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("EDI837Ingestion.EF.Entities.Diagnosis", b =>
                {
                    b.HasOne("EDI837Ingestion.EF.Entities.Claim", "Claim")
                        .WithMany("Diagnoses")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("EDI837Ingestion.EF.Entities.FunctionalGroup", b =>
                {
                    b.HasOne("EDI837Ingestion.EF.Entities.Interchange", "Interchange")
                        .WithMany("FunctionalGroups")
                        .HasForeignKey("InterchangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interchange");
                });

            modelBuilder.Entity("EDI837Ingestion.EF.Entities.TransactionSet", b =>
                {
                    b.HasOne("EDI837Ingestion.EF.Entities.FunctionalGroup", "FunctionalGroup")
                        .WithMany("TransactionSets")
                        .HasForeignKey("FunctionalGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EDI837Ingestion.EF.Entities.Interchange", "Interchange")
                        .WithMany()
                        .HasForeignKey("InterchangeId");

                    b.HasOne("EDI837Ingestion.EF.Entities.RawEdiFile", "RawEdiFile")
                        .WithMany()
                        .HasForeignKey("RawEdiFileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FunctionalGroup");

                    b.Navigation("Interchange");

                    b.Navigation("RawEdiFile");
                });

            modelBuilder.Entity("EDI837Ingestion.EF.Entities.ValidationIssue", b =>
                {
                    b.HasOne("EDI837Ingestion.EF.Entities.Claim", "Claim")
                        .WithMany()
                        .HasForeignKey("ClaimId");

                    b.HasOne("EDI837Ingestion.EF.Entities.TransactionSet", "TransactionSet")
                        .WithMany("ValidationIssues")
                        .HasForeignKey("TransactionSetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Claim");

                    b.Navigation("TransactionSet");
                });

            modelBuilder.Entity("EDI837Ingestion.EF.Entities.Claim", b =>
                {
                    b.Navigation("Diagnoses");

                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("EDI837Ingestion.EF.Entities.FunctionalGroup", b =>
                {
                    b.Navigation("TransactionSets");
                });

            modelBuilder.Entity("EDI837Ingestion.EF.Entities.Interchange", b =>
                {
                    b.Navigation("FunctionalGroups");
                });

            modelBuilder.Entity("EDI837Ingestion.EF.Entities.Payer", b =>
                {
                    b.Navigation("Claims");
                });

            modelBuilder.Entity("EDI837Ingestion.EF.Entities.TransactionSet", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("ValidationIssues");
                });
#pragma warning restore 612, 618
        }
    }
}
