// <auto-generated />
using System;
using EDI837Ingestion.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EDI837Ingestion.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EDI837Ingestion.EF.Entities.BillingProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Npi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BillingProviders");
                });

            modelBuilder.Entity("EDI837Ingestion.EF.Entities.ClaimBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FunctionalGroupId")
                        .HasColumnType("int");

                    b.Property<string>("PayerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubmitterContactPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubmitterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FunctionalGroupId");

                    b.ToTable("ClaimBatches");
                });

            modelBuilder.Entity("EDI837Ingestion.EF.Entities.ClaimDiagnosis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiagnosisCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiagnosisType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MedicalClaimId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MedicalClaimId");

                    b.ToTable("ClaimDiagnoses");
                });

            modelBuilder.Entity("EDI837Ingestion.EF.Entities.ClaimServiceLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("LineChargeAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int");

                    b.Property<int>("MedicalClaimId")
                        .HasColumnType("int");

                    b.Property<string>("ProcedureCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ServiceDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("UnitCount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MedicalClaimId");

                    b.ToTable("ClaimServiceLines");
                });

            modelBuilder.Entity("EDI837Ingestion.EF.Entities.FunctionalGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GroupControlNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InterchangeControlId")
                        .HasColumnType("int");

                    b.Property<string>("VersionCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InterchangeControlId");

                    b.ToTable("FunctionalGroups");
                });

            modelBuilder.Entity("EDI837Ingestion.EF.Entities.InterchangeControl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ControlNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TransmissionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("InterchangeControls");
                });

            modelBuilder.Entity("EDI837Ingestion.EF.Entities.MedicalClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BillingProviderId")
                        .HasColumnType("int");

                    b.Property<int>("ClaimBatchId")
                        .HasColumnType("int");

                    b.Property<string>("ClaimSubmitterIdentifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacilityCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StatementDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubscriberPatientId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalClaimChargeAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClaimBatchId");

                    b.ToTable("MedicalClaims");
                });

            modelBuilder.Entity("EDI837Ingestion.EF.Entities.SubscriberPatient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SubscriberPatients");
                });

            modelBuilder.Entity("EDI837Ingestion.EF.Entities.ClaimBatch", b =>
                {
                    b.HasOne("EDI837Ingestion.EF.Entities.FunctionalGroup", null)
                        .WithMany("ClaimBatches")
                        .HasForeignKey("FunctionalGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EDI837Ingestion.EF.Entities.ClaimDiagnosis", b =>
                {
                    b.HasOne("EDI837Ingestion.EF.Entities.MedicalClaim", null)
                        .WithMany("Diagnoses")
                        .HasForeignKey("MedicalClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EDI837Ingestion.EF.Entities.ClaimServiceLine", b =>
                {
                    b.HasOne("EDI837Ingestion.EF.Entities.MedicalClaim", null)
                        .WithMany("ServiceLines")
                        .HasForeignKey("MedicalClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EDI837Ingestion.EF.Entities.FunctionalGroup", b =>
                {
                    b.HasOne("EDI837Ingestion.EF.Entities.InterchangeControl", null)
                        .WithMany("FunctionalGroups")
                        .HasForeignKey("InterchangeControlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EDI837Ingestion.EF.Entities.MedicalClaim", b =>
                {
                    b.HasOne("EDI837Ingestion.EF.Entities.ClaimBatch", null)
                        .WithMany("MedicalClaims")
                        .HasForeignKey("ClaimBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EDI837Ingestion.EF.Entities.ClaimBatch", b =>
                {
                    b.Navigation("MedicalClaims");
                });

            modelBuilder.Entity("EDI837Ingestion.EF.Entities.FunctionalGroup", b =>
                {
                    b.Navigation("ClaimBatches");
                });

            modelBuilder.Entity("EDI837Ingestion.EF.Entities.InterchangeControl", b =>
                {
                    b.Navigation("FunctionalGroups");
                });

            modelBuilder.Entity("EDI837Ingestion.EF.Entities.MedicalClaim", b =>
                {
                    b.Navigation("Diagnoses");

                    b.Navigation("ServiceLines");
                });
#pragma warning restore 612, 618
        }
    }
}
