// <auto-generated />
using System;
using Edi837Ingestion.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Edi837Ingestion.Migrations
{
    [DbContext(typeof(Edi837DbContext))]
    partial class Edi837DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Edi837Ingestion.Persistence.Edi837DentalTransactionSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GroupControlNumber")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<int>("IngestedInterchangeId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("TransactionSetControlNumber")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.HasKey("Id");

                    b.HasIndex("IngestedInterchangeId");

                    b.ToTable("DentalTransactionSets");
                });

            modelBuilder.Entity("Edi837Ingestion.Persistence.Edi837InstitutionalTransactionSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GroupControlNumber")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<int>("IngestedInterchangeId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("TransactionSetControlNumber")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.HasKey("Id");

                    b.HasIndex("IngestedInterchangeId");

                    b.ToTable("InstitutionalTransactionSets");
                });

            modelBuilder.Entity("Edi837Ingestion.Persistence.Edi837ProfessionalTransactionSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GroupControlNumber")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<int>("IngestedInterchangeId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("TransactionSetControlNumber")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.HasKey("Id");

                    b.HasIndex("IngestedInterchangeId");

                    b.ToTable("ProfessionalTransactionSets");
                });

            modelBuilder.Entity("Edi837Ingestion.Persistence.IngestedInterchange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("InterchangeControlNumber")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("PayloadS3Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReceiverId")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash")
                        .IsUnique()
                        .HasDatabaseName("IX_Interchanges_ContentHash");

                    b.ToTable("Interchanges");
                });

            modelBuilder.Entity("Edi837Ingestion.Persistence.Edi837DentalTransactionSet", b =>
                {
                    b.HasOne("Edi837Ingestion.Persistence.IngestedInterchange", "Interchange")
                        .WithMany()
                        .HasForeignKey("IngestedInterchangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interchange");
                });

            modelBuilder.Entity("Edi837Ingestion.Persistence.Edi837InstitutionalTransactionSet", b =>
                {
                    b.HasOne("Edi837Ingestion.Persistence.IngestedInterchange", "Interchange")
                        .WithMany()
                        .HasForeignKey("IngestedInterchangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interchange");
                });

            modelBuilder.Entity("Edi837Ingestion.Persistence.Edi837ProfessionalTransactionSet", b =>
                {
                    b.HasOne("Edi837Ingestion.Persistence.IngestedInterchange", "Interchange")
                        .WithMany()
                        .HasForeignKey("IngestedInterchangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interchange");
                });
#pragma warning restore 612, 618
        }
    }
}
