services:
  db:
    image: mcr.microsoft.com/mssql/server:2025-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong@Passw0rd"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    security_opt:
      - seccomp:unconfined

  moto:
    image: motoserver/moto
    ports:
      - "5001:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/moto-api/"]
      interval: 2s
      retries: 10

  moto-init:
    image: alpine:latest
    depends_on:
      moto:
        condition: service_healthy
    environment:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: us-east-1
      AWS_PAGER: ""
    volumes:
      - ./infra/init.sh:/init.sh
    command: ["/bin/sh", "-c", "apk add --no-cache aws-cli && /bin/sh /init.sh"]
