// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using X12EDI837Ingestion.Domain;

#nullable disable

namespace X12EDI837Ingestion.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260302025412_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("X12EDI837Ingestion.Domain.Entities.Claim", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ClaimFilingIndicator")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ClaimFrequencyCode")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("ClaimSubmitterId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacilityCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacilityTypeCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PatientControlNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RawSegment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<long?>("SubscriberPartyId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("TotalClaimChargeAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("TransactionSetHeaderId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PatientControlNumber");

                    b.HasIndex("SubscriberPartyId");

                    b.HasIndex("TransactionSetHeaderId");

                    b.ToTable("Claims", (string)null);
                });

            modelBuilder.Entity("X12EDI837Ingestion.Domain.Entities.FunctionalGroupHeader", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FunctionalIdCode")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("FunctionalIdentifierCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupControlNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("GroupDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("InterchangeHeaderId")
                        .HasColumnType("bigint");

                    b.Property<string>("RawSegment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ReceiverCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SenderCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Time")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Version")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("InterchangeHeaderId", "GroupControlNumber");

                    b.ToTable("FunctionalGroupHeaders", (string)null);
                });

            modelBuilder.Entity("X12EDI837Ingestion.Domain.Entities.InterchangeHeader", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AuthorizationInfoQualifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ControlNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("InterchangeControlNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InterchangeDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("RawSegment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReceiverId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReceiverIdQualifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityInfoQualifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SenderIdQualifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Time")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ControlNumber");

                    b.ToTable("InterchangeHeaders", (string)null);
                });

            modelBuilder.Entity("X12EDI837Ingestion.Domain.Entities.Party", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("EntityIdentifierCode")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("EntityTypeQualifier")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("IdCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdCodeQualifier")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("LastNameOrOrgName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RawSegment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("TransactionSetHeaderId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TransactionSetHeaderId", "Role");

                    b.ToTable("Parties", (string)null);
                });

            modelBuilder.Entity("X12EDI837Ingestion.Domain.Entities.ServiceLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClaimId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("LineItemChargeAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PlaceOfService")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ProcedureCode")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("RawSegment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal?>("UnitCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UnitOrBasis")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.ToTable("ServiceLines", (string)null);
                });

            modelBuilder.Entity("X12EDI837Ingestion.Domain.Entities.TransactionSetHeader", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BhtReferenceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FunctionalGroupHeaderId")
                        .HasColumnType("bigint");

                    b.Property<string>("HierarchicalStructureCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ImplementationConvention")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RawBhtSegment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("RawStSegment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("TransactionDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionSetControlNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TransactionSetId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionSetIdCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TransactionSetPurposeCode")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("Id");

                    b.HasIndex("FunctionalGroupHeaderId", "TransactionSetControlNumber");

                    b.ToTable("TransactionSetHeaders", (string)null);
                });

            modelBuilder.Entity("X12EDI837Ingestion.Domain.Entities.Claim", b =>
                {
                    b.HasOne("X12EDI837Ingestion.Domain.Entities.Party", "SubscriberParty")
                        .WithMany()
                        .HasForeignKey("SubscriberPartyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("X12EDI837Ingestion.Domain.Entities.TransactionSetHeader", "TransactionSetHeader")
                        .WithMany("Claims")
                        .HasForeignKey("TransactionSetHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubscriberParty");

                    b.Navigation("TransactionSetHeader");
                });

            modelBuilder.Entity("X12EDI837Ingestion.Domain.Entities.FunctionalGroupHeader", b =>
                {
                    b.HasOne("X12EDI837Ingestion.Domain.Entities.InterchangeHeader", "InterchangeHeader")
                        .WithMany("FunctionalGroups")
                        .HasForeignKey("InterchangeHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InterchangeHeader");
                });

            modelBuilder.Entity("X12EDI837Ingestion.Domain.Entities.Party", b =>
                {
                    b.HasOne("X12EDI837Ingestion.Domain.Entities.TransactionSetHeader", "TransactionSetHeader")
                        .WithMany("Parties")
                        .HasForeignKey("TransactionSetHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TransactionSetHeader");
                });

            modelBuilder.Entity("X12EDI837Ingestion.Domain.Entities.ServiceLine", b =>
                {
                    b.HasOne("X12EDI837Ingestion.Domain.Entities.Claim", "Claim")
                        .WithMany("ServiceLines")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("X12EDI837Ingestion.Domain.Entities.TransactionSetHeader", b =>
                {
                    b.HasOne("X12EDI837Ingestion.Domain.Entities.FunctionalGroupHeader", "FunctionalGroupHeader")
                        .WithMany("TransactionSets")
                        .HasForeignKey("FunctionalGroupHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FunctionalGroupHeader");
                });

            modelBuilder.Entity("X12EDI837Ingestion.Domain.Entities.Claim", b =>
                {
                    b.Navigation("ServiceLines");
                });

            modelBuilder.Entity("X12EDI837Ingestion.Domain.Entities.FunctionalGroupHeader", b =>
                {
                    b.Navigation("TransactionSets");
                });

            modelBuilder.Entity("X12EDI837Ingestion.Domain.Entities.InterchangeHeader", b =>
                {
                    b.Navigation("FunctionalGroups");
                });

            modelBuilder.Entity("X12EDI837Ingestion.Domain.Entities.TransactionSetHeader", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("Parties");
                });
#pragma warning restore 612, 618
        }
    }
}
