// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace H2.EdiIngestor.Migrations
{
    [DbContext(typeof(EdiIngestorDbContext))]
    partial class EdiIngestorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("H2.EdiIngestor.Data.Claim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BillingProviderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BillingProviderNpi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RenderingProviderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RenderingProviderNpi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubscriberId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("H2.EdiIngestor.Data.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ChargeAmount")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<int?>("ClaimId")
                        .HasColumnType("int");

                    b.Property<string>("DiagnosisCode1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiagnosisCode2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiagnosisCode3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiagnosisCode4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProcedureCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UnitOrBasisForMeasurementCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("H2.EdiIngestor.Data.Service", b =>
                {
                    b.HasOne("H2.EdiIngestor.Data.Claim", "Claim")
                        .WithMany("Services")
                        .HasForeignKey("ClaimId");

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("H2.EdiIngestor.Data.Claim", b =>
                {
                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
