#!/usr/bin/env bash
set -Eeuo pipefail

export AWS_ENDPOINT_URL="${AWS_ENDPOINT_URL:-http://localhost:3000}"
export AWS_ACCESS_KEY_ID="fake-access-key-id"
export AWS_SECRET_ACCESS_KEY="fake-secret-access-key"
export AWS_DEFAULT_REGION="${AWS_DEFAULT_REGION:-us-east-1}"

exec aws "$@"
