name: EDI 837 Build and Test

on:
  push:
    branches: [ main, develop, feature/*, clint-s-837-injest-djh ]
    paths:
      - 'clint_smith/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'clint_smith/**'
      - '.github/workflows/**'
  workflow_dispatch: # Allows manual triggering

jobs:
  edi-build-test:
    name: EDI 837 Ingestion Build and Test
    uses: ./.github/workflows/dotnet-build-test-template.yml
    with:
      SOLUTION_FILE: "EDI837.Ingestion.sln"
      WORKING_DIRECTORY: "clint_smith"
      DOTNET_VERSION: "8.x"
      BUILD_CONFIGURATION: "Release"
      TARGET_FRAMEWORK: "net8.0"
      UNIT_TEST_FILTER: "Category=Unit|TestCategory=UnitTest"
      RUN_SPECFLOW_TESTS: false
    secrets:
      REGISTRY_USER: ${{ secrets.GITHUB_TOKEN }}
      REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}