name: Simple EDI Test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Test workflow
        run: |
          echo "Workflow is working!"
          echo "Current branch: ${{ github.ref_name }}"
          echo "Repository: ${{ github.repository }}"
          ls -la